<a href="https://colab.research.google.com/github/yigagilbert/blood-donatio-model/blob/main/prediction_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import  Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
train = pd.read_csv('/content/gdrive/MyDrive/blood-donation-dataset/blood-train.csv')
test = pd.read_csv('/content/gdrive/MyDrive/blood-donation-dataset/blood-test.csv')
train.head()

Unnamed: 0  Months since Last Donation  Number of Donations  \
0         619                           2                   50   
1         664                           0                   13   
2         441                           1                   16   
3         160                           2                   20   
4         358                           1                   24   

   Total Volume Donated (c.c.)  Months since First Donation  \
0                        12500                           98   
1                         3250                           28   
2                         4000                           35   
3                         5000                           45   
4                         6000                           77   

   Made Donation in March 2007  
0                            1  
1                            1  
2                            1  
3                            1  
4                            0

In [ ]:
dataframe=pd.read_csv('/content/gdrive/MyDrive/blood-donation-dataset/blood-train.csv')
dataset=dataframe.values
print(dataset)

[[  619     2    50 12500    98     1]
 [  664     0    13  3250    28     1]
 [  441     1    16  4000    35     1]
 ...
 [  360    21     2   500    52     0]
 [  541    39     1   250    39     0]
 [   74    72     1   250    72     0]]


In [ ]:
x=dataset[:,0:5]
print(x.shape)
y=dataset[:,-1]
y=np.reshape(y, (-1,1))
print(y.shape)

# need to scale,bt before it need to it can do in flutter
# scaler_x = MinMaxScaler()
# scaler_y = MinMaxScaler()
# print(scaler_x.fit(x))
# xscale=scaler_x.transform(x)
# print(scaler_y.fit(y))
# yscale=scaler_y.transform(y)


(576, 5)
(576, 1)


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
# 75% 25%
# print(y_test.shape)

In [ ]:
model=Sequential()
model.add(Dense(12,input_dim=5,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                72        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mse',optimizer='adam',metrics=['mse','mae'])

In [ ]:
history= model.fit(x_train,y_train,epochs=250,batch_size=20)

Epoch 1/250
22/22 [==============================] - 0s 2ms/step - loss: 0.9003 - mse: 0.9003 - mae: 0.6939
Epoch 2/250
22/22 [==============================] - 0s 2ms/step - loss: 0.6216 - mse: 0.6216 - mae: 0.5943
Epoch 3/250
22/22 [==============================] - 0s 2ms/step - loss: 0.5823 - mse: 0.5823 - mae: 0.5636
Epoch 4/250
22/22 [==============================] - 0s 2ms/step - loss: 0.5133 - mse: 0.5133 - mae: 0.5429
Epoch 5/250
22/22 [==============================] - 0s 2ms/step - loss: 0.4316 - mse: 0.4316 - mae: 0.4885
Epoch 6/250
22/22 [==============================] - 0s 1ms/step - loss: 0.6658 - mse: 0.6658 - mae: 0.6065
Epoch 7/250
22/22 [==============================] - 0s 2ms/step - loss: 0.4564 - mse: 0.4564 - mae: 0.5119
Epoch 8/250
22/22 [==============================] - 0s 2ms/step - loss: 0.5393 - mse: 0.5393 - mae: 0.5356
Epoch 9/250
22/22 [==============================] - 0s 2ms/step - loss: 0.4193 - mse: 0.4193 - mae: 0.4940
Epoch 10/250
22/22 [========

In [ ]:
xnew=np.array([[913,1072,1595,3736,5340]])
ynew= model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[360  21   2 500  52], Predicted=[-0.3804008]


In [ ]:
model.save('/content/predtest.h5')

In [ ]:
from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('/content/predtest.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

2344

In [ ]:
xnew=np.array([[913,1072,1595,3736,5340]])
ynew= modelnew.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[ 913 1072 1595 3736 5340], Predicted=[3213.0403]


In [ ]:
# print(history.history.keys())
# # "Loss"
# plt.plot(history.history['loss'])
# plt.plot(history.history['mse'])
# plt.title('model loss')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train', 'validation'], loc='upper left')
# plt.show()